import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the web repo's build and copied here to be served as a
    // static asset. It is a browser bundle, not source, and linting it only
    // produces unused-export warnings for the simulators the marketing site
    // has not mounted on a given page.
    "public/afriorbit-sims.js",
  ]),
]);

export default eslintConfig;
